// Copyright (c) Piet Wauters 2026 <piet.wauters@gmail.com>
// Tier A (certificate-based) provisioning, docs/level2.md §30.5. Generates this
// device's own keypair + CSR locally (the private key never leaves the device),
// exchanges it for a signed certificate over MQTT, and persists both for future
// mTLS connections to the broker. See Atlas's services/provisioning.js for the
// CMS-side counterpart of this exchange.
#ifndef TIER_A_PROVISIONING_H
#define TIER_A_PROVISIONING_H
#include "Singleton.h"
#include <string>

class TierAProvisioning : public SingletonMixin<TierAProvisioning> {
public:
  // Stable per-device id, derived from the MAC address on first call and
  // persisted thereafter (NVS namespace "tier_a"). Also the provisioning
  // response topic's correlation segment.
  std::string GetOrCreateDeviceId();

  // Whether a previously-granted certificate is stored in NVS.
  bool HasCertificate();

  // Diagnostic-only: byte lengths of each NVS entry ("cert"/"priv_key"/
  // "ca_cert"), plus whether a request is currently pending — so the /provision
  // page can show real ground truth instead of just a yes/no summary. Never
  // exposes the actual key/cert contents.
  struct StorageDebugInfo {
    size_t certLen;
    size_t privKeyLen;
    size_t caCertLen;
    bool requestPending;
    unsigned long requestAgeMs; // only meaningful if requestPending
  };
  StorageDebugInfo GetStorageDebugInfo();

  // Applies whatever is currently stored in NVS to the shared MQTT client
  // (setTlsCerts + setTLS(true, ...)) — call before AtlasAsyncMqttClient::begin()
  // if HasCertificate() is true. No-op if nothing is stored.
  void LoadStoredCertsIntoClient();

  // Generates a fresh EC keypair + CSR, subscribes to this device's own response
  // topic, and publishes the _provision/request. `role` is one of
  // apparatus|scoresheet|remote|var. Returns false immediately on a local error
  // (e.g. key generation failure); the actual grant/deny arrives later via
  // HandleResponse(), asynchronously.
  bool GenerateAndRequest(const char *code, const char *role,
                          const char *deviceLabel = nullptr);

  // Called by Opp2Handler::OnMqttMessageStatic when a message arrives on this
  // device's openpiste/_provision/response/{device_id} topic. On a grant, this
  // applies the certificate to the MQTT client and stages a reconnect — it does
  // NOT perform the reconnect itself. See ApplyReconnectIfPending().
  void HandleResponse(const char *payload, size_t length);

  // Must be called once per main-loop iteration, from a context outside the MQTT
  // client's own event handler (Opp2Handler::CheckConnection(), called from
  // loop() in main.cpp, qualifies). No-op unless HandleResponse() staged a
  // reconnect. Split out from HandleResponse() because
  // esp_mqtt_client_stop()/_destroy() (which the actual reconnect needs) MUST
  // NOT be called from inside the MQTT client's own task — confirmed on real
  // hardware: doing so logs "Client cannot be stopped from MQTT task" and then
  // crashes with a FreeRTOS mutex assertion failure shortly after.
  void ApplyReconnectIfPending();

private:
  friend class SingletonMixin<TierAProvisioning>;
  TierAProvisioning() = default;

  std::string m_deviceId;
  // The private key generated by the most recent GenerateAndRequest() call,
  // held in memory only until HandleResponse() confirms a grant and persists it
  // (or a denial discards it) — never written to NVS before that.
  std::string m_pendingKeyPem;

  // Guards against a second GenerateAndRequest() call clobbering m_pendingKeyPem
  // while a request is still in flight — e.g. a browser resubmitting the
  // /provision form on refresh. Auto-expires after PENDING_TIMEOUT_MS so a
  // response that never arrives (CMS unreachable) doesn't permanently lock the
  // device out of retrying.
  bool m_requestPending = false;
  unsigned long m_requestSentAtMs = 0;
  static const unsigned long PENDING_TIMEOUT_MS = 30000;

  // Set by HandleResponse() on a grant, consumed by ApplyReconnectIfPending() —
  // see the comment on that method for why this hand-off exists at all.
  bool m_reconnectPending = false;
};

#endif // TIER_A_PROVISIONING_H
